### ISSUE TITLE
Copying existing activities 

### ISSUE THREAD

**Issue by okputadora** [mathematicalthinking/vmt#90]
When you copy an activity you should be redirected back to community/activities

**Comment by willamesoares** [comment]
I see no one is working on this, so am I good to give it a try?

**Comment by okputadora** [comment]
@willamesoares Hi, sorry, just seeing this. Yes, you can work on it. Let us know if you need help getting the repo setup locally.

**Comment by willamesoares** [comment]
Hi, yeah I had issues while setting up the project and couldn't really use the time I saved to work on this since I was blocked.
I couple of other things came up and I'm still handling them so I'm freeing this issue up so someone else can take a look at it.

Thanks for the answer and sorry for this.

**Comment by okputadora** [comment]
@willemsoares no worries. Feel free to pick up another issue in the future if you like. Also, if you wouldn't mind sharing what was preventing you from getting the project setup it might help us prevent that problem for other contributors.
